name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - name: Generate report
        run: npm run cy:posttest
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress/reports/
        env:
          CYPRESS_RECORD_KEY: 82782773-8af9-4fa0-8b3c-30b7a3bdc322
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: 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
